### ISSUE TITLE
runtime error when I ran training 

### ISSUE THREAD

**Issue by xuzhang5788** [PaccMann/paccmann_sarscov2#6]
Thank you for your repo.
When I ran 
(paccmann_sarscov2) $ python ./code/paccmann_generator/examples/affinity/train_conditional_generator.py \
    ./models/SELFIESVAE \
    ./models/ProteinVAE \
    ./models/affinity \
    ./data/training/merged_sequence_encoding/uniprot_covid-19.csv \
    ./code/paccmann_generator/examples/affinity/conditional_generator.json \
    paccmann_sarscov2 \
    35 \
    ./data/training/unbiased_predictions \
    --tox21_path ./models/Tox21

I got the following error messages:

INFO:train_paccmann_rl:Model with name paccmann_sarscov2_35 starts.
INFO:train_paccmann_rl:Test protein is ACE2_HUMAN
WARNING:train_paccmann_rl:Model exists already. Call model.load() to restore weights.
INFO:train_paccmann_rl:Model stored at biased_models/paccmann_sarscov2_35
INFO:train_paccmann_rl:Current train protein: NS8B_CVHSA
Traceback (most recent call last):
  File "./code/paccmann_generator/examples/affinity/train_conditional_generator.py", line 324, in <module>
    main(parser_namespace=args)
  File "./code/paccmann_generator/examples/affinity/train_conditional_generator.py", line 244, in main
    protein_name, epoch, params['batch_size']
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_generator/reinforce_proteins.py", line 298, in policy_gradient
    latent_z, remove_invalid=True
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_generator/reinforce.py", line 169, in get_smiles_from_latent
    search=SamplingSearch(temperature=self.temperature)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/vae.py", line 640, in generate
    generate_len=generate_len
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/vae.py", line 457, in generate_from_latent
    output, hidden, stack = self(input_token, hidden, stack)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/stack_rnn.py", line 153, in forward
    gru_input, stack = self.update(embedded_input, hidden, stack)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/stack_rnn.py", line 62, in <lambda>
    inp, hidden, stack
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/stack_rnn.py", line 195, in _stack_update
    stack_input.permute(1, 0, 2), stack, stack_controls
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/paccmann_chemistry/models/stack_rnn.py", line 228, in stack_augmentation
    stack_up = torch.cat((input_val, prev_stack[:, :-1]), dim=1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument tensors in method wrapper__cat)

When I tried 

(paccmann_sarscov2) $ python ./code/toxsmi/scripts/train_tox.py \
    ./data/pretraining/toxicity_predictor/tox21_train.csv \
    ./data/pretraining/toxicity_predictor/tox21_test.csv \
    ./data/pretraining/toxicity_predictor/tox21.smi \
    ./data/pretraining/language_models/smiles_language_tox21.pkl \
    ./models/ \
    ./code/toxsmi/params/mca.json \
    Tox21 \
    --embedding_path ./data/pretraining/toxicity_predictor/smiles_vae_embeddings.pkl

similar errors occurred:

INFO:Tox21:mca.json
INFO:Tox21:== Epoch [0/200] ==
Traceback (most recent call last):
  File "./code/toxsmi/scripts/train_tox.py", line 420, in <module>
    args.params_filepath, args.training_name, args.embedding_path
  File "./code/toxsmi/scripts/train_tox.py", line 284, in main
    loss = model.loss(y_hat, y.to(device))
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/toxsmi/models/mca.py", line 307, in loss
    return self.loss_fn(yhat, y)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/toxsmi/utils/wrappers.py", line 76, in forward
    out = loss * weight_tensor
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by jannisborn** [comment]
Hi @xuzhang5788, thanks for reporting this issue. This is a device mismatch across CPU and GPU. You have to make sure that when you load a model from an existing checkpoint via `torch.load` that it's loaded to the correct device. You can use `map_location='cpu'` or `'cuda'` if both devices are available. Hope this helps!

PS: If you execute the code on a machine _without_  GPU access, it will most likely run through without any adaptation

**Comment by xuzhang5788** [comment]
Thank you so much for your fast response.
I have one GPU. I think your code will detect GPU or CPU automatically in /paccmann_sarscov2/code/paccmann_chemistry/paccmann_chemistry/utils/utils.py. I checked it. It outputed DEVICE is cuda.

**Comment by jannisborn** [comment]
Yes exactly. If you want to run it with GPU, the quick fix is to cast the weight_tensor to GPU. This weight tensor is independent of the model so it's not detected in the utility you mentioned.

**Comment by xuzhang5788** [comment]
Thank you again. 
I am sorry that I am not very familiar with pytorch. I couldn't find where and how to do this quick fix. Could you please tell me how to fix it? Many thanks!

# Restore SMILES Model
    with open(os.path.join(mol_model_path, 'model_params.json')) as f:
        mol_params = json.load(f)

    gru_encoder = StackGRUEncoder(mol_params)
    gru_decoder = StackGRUDecoder(mol_params)
    generator = TeacherVAE(gru_encoder, gru_decoder)
    generator.load(
        os.path.join(
            mol_model_path,
            f"weights/best_{params.get('smiles_metric', 'rec')}.pt"
        ),
        map_location=get_device()
    )
Here it already sets map_location to cuda.

**Comment by jannisborn** [comment]
The error comes from line 76 in 
`/home/xzhang/miniconda3/envs/paccmann_sarscov2/lib/python3.7/site-packages/toxsmi/utils/wrappers.py`.
Go there and cast the weight tensor to the device where you want it to be (cuda in your case).

As you can read from the package location, the error comes from a downstream dependency package called `toxsmi`. The error was even fixed in the current master branch of `toxsmi` see [here](https://github.com/PaccMann/toxsmi/blob/master/toxsmi/utils/wrappers.py). 

It doesnt have anything to do with the TeacherVAE. The TeacherVAE model is the molecule generator. The error comes from the toxicity prediction model implemented in `toxsmi`.

**Comment by xuzhang5788** [comment]
Sorry for asking questions again. 
I met this kind of error twice. toxsmi is one of them. The critical one is to run ./code/paccmann_generator/examples/affinity/train_conditional_generator.py. I showed it at the beginning.

**Comment by jannisborn** [comment]
In the first case, the error trace says that the data (input_val) is stored on CPU whereas the model weights (in this case prev_stack) is on GPU. You just have to change the code and send the tensors to the devices where you want them to be. If you want to prevent this juggling with sending tensors around, you can consider globally disabling the GPU, e.g. [like this](https://stackoverflow.com/a/53266932/6383205)

**Comment by xuzhang5788** [comment]
Thank you very much. I will try it
